import { getRuleDefinition } from "@/features/actions-analyzer/lib/rule-catalog";
import { sortFindings } from "@/features/actions-analyzer/lib/scoring";
import type {
  AnalyzerFinding,
  Severity,
  WorkflowAnalysisReport,
} from "@/features/actions-analyzer/types";

export interface SarifArtifactLocation {
  uri: string;
}

export interface SarifPhysicalLocation {
  artifactLocation: SarifArtifactLocation;
  region?:
    | {
        endColumn?: number | undefined;
        endLine?: number | undefined;
        startColumn?: number | undefined;
        startLine?: number | undefined;
      }
    | undefined;
}

export interface SarifLocation {
  physicalLocation: SarifPhysicalLocation;
}

export interface SarifResult {
  level: "error" | "note" | "warning";
  locations: SarifLocation[];
  message: {
    text: string;
  };
  properties: {
    category: string;
    confidence: string;
    relatedJobs: string[];
    relatedSteps: string[];
    severity: Severity;
  };
  ruleId: string;
}

export interface SarifRule {
  fullDescription: {
    text: string;
  };
  helpUri?: string | undefined;
  id: string;
  name: string;
  properties: {
    category: string;
    defaultSeverity: Severity;
    tags: string[];
  };
  shortDescription: {
    text: string;
  };
}

export interface SarifLog {
  $schema: string;
  runs: Array<{
    results: SarifResult[];
    tool: {
      driver: {
        informationUri: string;
        name: string;
        rules: SarifRule[];
      };
    };
  }>;
  version: "2.1.0";
}

export function buildPrCommentMarkdown(report: WorkflowAnalysisReport) {
  const topFindings = sortFindings(report.findings).slice(0, 10);
  const unpinnedActionCount = report.actionInventory.filter(
    (item) => !item.pinned,
  ).length;
  const privilegedActionCount = report.actionInventory.filter(
    (item) => item.isPrivileged,
  ).length;
  const highRiskJobCount = report.permissionSummary.jobRecommendations.filter(
    (recommendation) => recommendation.riskLabel === "high",
  ).length;
  const lines = [
    `## Authos Review: ${report.summary.score}/100 (${report.summary.grade})`,
    "",
    `- Critical findings: ${report.summary.severityCounts.critical}`,
    `- High findings: ${report.summary.severityCounts.high}`,
    `- Total findings: ${report.summary.totalFindings}`,
    "",
    "### Top findings",
    "",
  ];

  if (topFindings.length === 0) {
    lines.push("- No findings for enabled rules.");
  } else {
    for (const finding of topFindings) {
      lines.push(
        `- [${finding.severity}] ${finding.ruleId} ${finding.title} (${formatFindingLocation(finding)})`,
      );
      lines.push(`  ${finding.message}`);
    }
  }

  lines.push(
    "",
    "### Action pinning summary",
    "",
    `- Action references reviewed: ${report.actionInventory.length}`,
    `- Unpinned references: ${unpinnedActionCount}`,
    `- Privileged references: ${privilegedActionCount}`,
    "",
    "### Permission summary",
    "",
    `- Workflows missing top-level permissions: ${report.permissionSummary.missingPermissions.length}`,
    `- Recommended baseline: ${report.permissionSummary.recommendedPermissions.join(", ") || "None"}`,
    `- Higher-review-risk jobs: ${highRiskJobCount}`,
  );

  if (report.matrixSummary.totalJobs > 0) {
    lines.push(
      "",
      "### Matrix summary",
      "",
      `- Matrix jobs: ${report.matrixSummary.totalJobs}`,
      `- Max static combinations: ${report.matrixSummary.maxCombinations}`,
      `- Matrix warnings: ${report.matrixSummary.warningCount}`,
    );
  }

  lines.push(
    "",
    `_Generated by Authos locally on ${formatDate(report.generatedAt)}._`,
  );

  return lines.join("\n");
}

export function serializeReportAsJson(report: WorkflowAnalysisReport) {
  return JSON.stringify(report, null, 2);
}

export function buildSarifReport(report: WorkflowAnalysisReport): SarifLog {
  const rules = Array.from(
    new Map(
      report.findings.map((finding) => {
        const definition = getRuleDefinition(finding.ruleId);

        return [
          finding.ruleId,
          {
            fullDescription: {
              text:
                definition?.description ??
                finding.remediation ??
                finding.message,
            },
            helpUri: definition?.docsUrl ?? finding.docsUrl,
            id: finding.ruleId,
            name: definition?.title ?? finding.title,
            properties: {
              category: definition?.category ?? finding.category,
              defaultSeverity: definition?.defaultSeverity ?? finding.severity,
              tags: definition?.tags ?? finding.tags,
            },
            shortDescription: {
              text: finding.title,
            },
          } satisfies SarifRule,
        ];
      }),
    ).values(),
  );

  return {
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    runs: [
      {
        results: report.findings.map((finding) => ({
          level: toSarifLevel(finding.severity),
          locations: [
            {
              physicalLocation: {
                artifactLocation: {
                  uri: normalizeFilePath(finding.filePath),
                },
                region: finding.location
                  ? {
                      endColumn: finding.location.endColumn,
                      endLine: finding.location.endLine,
                      startColumn: finding.location.column,
                      startLine: finding.location.line,
                    }
                  : undefined,
              },
            },
          ],
          message: {
            text: finding.message,
          },
          properties: {
            category: finding.category,
            confidence: finding.confidence,
            relatedJobs: finding.relatedJobs,
            relatedSteps: finding.relatedSteps,
            severity: finding.severity,
          },
          ruleId: finding.ruleId,
        })),
        tool: {
          driver: {
            informationUri: "https://authos.local",
            name: "Authos GitHub Actions Analyzer",
            rules,
          },
        },
      },
    ],
    version: "2.1.0",
  };
}

export function buildHtmlReport(report: WorkflowAnalysisReport) {
  const escapedTitle = escapeHtml(
    `Authos Report ${report.summary.score}/100 (${report.summary.grade})`,
  );
  const findingsMarkup =
    report.findings.length === 0
      ? '<p class="empty">No findings for enabled rules.</p>'
      : sortFindings(report.findings)
          .map((finding) => {
            return [
              '<article class="finding">',
              `<div class="finding-meta"><span class="badge severity-${escapeHtml(
                finding.severity,
              )}">${escapeHtml(finding.severity)}</span><span class="badge">${escapeHtml(
                finding.ruleId,
              )}</span><span>${escapeHtml(formatFindingLocation(finding))}</span></div>`,
              `<h2>${escapeHtml(finding.title)}</h2>`,
              `<p>${escapeHtml(finding.message)}</p>`,
              `<p class="muted">Confidence: ${escapeHtml(
                finding.confidence,
              )} / Category: ${escapeHtml(finding.category)}</p>`,
              "</article>",
            ].join("");
          })
          .join("");

  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    `<title>${escapedTitle}</title>`,
    "<style>",
    "body{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#0f172a;color:#e2e8f0;margin:0;padding:32px;line-height:1.6}",
    "main{max-width:980px;margin:0 auto}",
    ".hero,.panel,.finding{border:1px solid #334155;border-radius:16px;background:#111827;padding:20px}",
    ".hero{margin-bottom:20px}",
    ".grid{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));margin:20px 0}",
    ".metric{border:1px solid #334155;border-radius:12px;padding:14px;background:#0f172a}",
    ".muted{color:#94a3b8}",
    ".badge{display:inline-block;border:1px solid #475569;border-radius:999px;padding:2px 10px;margin-right:8px;font-size:12px;text-transform:uppercase}",
    ".severity-critical,.severity-high{border-color:#f87171;color:#fecaca}",
    ".severity-medium{border-color:#f59e0b;color:#fde68a}",
    ".severity-low{border-color:#38bdf8;color:#bae6fd}",
    ".severity-info{border-color:#a78bfa;color:#ddd6fe}",
    ".finding{margin-top:16px}",
    ".finding-meta{margin-bottom:8px;color:#94a3b8;font-size:13px}",
    ".empty{border:1px dashed #475569;border-radius:12px;padding:20px;background:#111827}",
    "</style>",
    "</head>",
    "<body>",
    "<main>",
    `<section class="hero"><h1>${escapedTitle}</h1><p class="muted">Generated by Authos locally on ${escapeHtml(
      formatDate(report.generatedAt),
    )}.</p></section>`,
    '<section class="panel">',
    '<div class="grid">',
    renderMetric("Critical", String(report.summary.severityCounts.critical)),
    renderMetric("High", String(report.summary.severityCounts.high)),
    renderMetric("Files", String(report.summary.analyzedFileCount)),
    renderMetric("Jobs", String(report.summary.jobCount)),
    renderMetric("Actions", String(report.actionInventory.length)),
    renderMetric("Matrix jobs", String(report.matrixSummary.totalJobs)),
    "</div>",
    "</section>",
    '<section class="panel" style="margin-top:20px">',
    "<h2>Findings</h2>",
    findingsMarkup,
    "</section>",
    "</main>",
    "</body>",
    "</html>",
  ].join("");
}

function renderMetric(label: string, value: string) {
  return `<div class="metric"><div class="muted">${escapeHtml(
    label,
  )}</div><div>${escapeHtml(value)}</div></div>`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/gu, "&amp;")
    .replace(/</gu, "&lt;")
    .replace(/>/gu, "&gt;")
    .replace(/"/gu, "&quot;")
    .replace(/'/gu, "&#39;");
}

function formatFindingLocation(finding: AnalyzerFinding) {
  return finding.location
    ? `${finding.filePath}:${finding.location.line}`
    : finding.filePath;
}

function formatDate(value: string) {
  return new Date(value).toISOString();
}

function normalizeFilePath(filePath: string) {
  return filePath.replace(/\\/gu, "/");
}

function toSarifLevel(severity: Severity) {
  switch (severity) {
    case "critical":
    case "high":
      return "error";
    case "medium":
      return "warning";
    case "low":
    case "info":
    default:
      return "note";
  }
}
