import { sortFindings } from "@/features/actions-analyzer/lib/scoring";
import type {
  AnalyzerFinding,
  WorkflowAnalysisReport,
} from "@/features/actions-analyzer/types";

export interface ComparedFindingPair {
  current: AnalyzerFinding;
  key: string;
  previous: AnalyzerFinding;
}

export interface ReportComparisonSummary {
  newFindingCount: number;
  newHighOrCriticalCount: number;
  resolvedFindingCount: number;
  scoreDelta: number;
  unchangedFindingCount: number;
}

export interface WorkflowReportComparison {
  newFindings: AnalyzerFinding[];
  previousReport: WorkflowAnalysisReport;
  resolvedFindings: AnalyzerFinding[];
  summary: ReportComparisonSummary;
  unchangedFindings: ComparedFindingPair[];
}

export function createStableFindingKey(finding: AnalyzerFinding) {
  const line = finding.location?.line ?? 0;
  const column = finding.location?.column ?? 0;
  const endLine = finding.location?.endLine ?? 0;
  const endColumn = finding.location?.endColumn ?? 0;
  const normalizedFilePath = normalizeFilePath(finding.filePath);
  const relatedJobs = [...finding.relatedJobs].sort().join(",");
  const relatedSteps = [...finding.relatedSteps].sort().join(",");

  return [
    finding.ruleId,
    normalizedFilePath,
    line,
    column,
    endLine,
    endColumn,
    relatedJobs,
    relatedSteps,
  ].join("::");
}

export function compareWorkflowReports(
  currentReport: WorkflowAnalysisReport,
  previousReport: WorkflowAnalysisReport,
): WorkflowReportComparison {
  const currentByKey = new Map(
    currentReport.findings.map((finding) => [
      createStableFindingKey(finding),
      finding,
    ]),
  );
  const previousByKey = new Map(
    previousReport.findings.map((finding) => [
      createStableFindingKey(finding),
      finding,
    ]),
  );
  const newFindings = sortFindings(
    currentReport.findings.filter((finding) => {
      return !previousByKey.has(createStableFindingKey(finding));
    }),
  );
  const resolvedFindings = sortFindings(
    previousReport.findings.filter((finding) => {
      return !currentByKey.has(createStableFindingKey(finding));
    }),
  );
  const unchangedFindings = sortFindings(
    currentReport.findings.filter((finding) => {
      return previousByKey.has(createStableFindingKey(finding));
    }),
  ).flatMap<ComparedFindingPair>((finding) => {
    const key = createStableFindingKey(finding);
    const previousFinding = previousByKey.get(key);

    return previousFinding
      ? [
          {
            current: finding,
            key,
            previous: previousFinding,
          },
        ]
      : [];
  });

  return {
    newFindings,
    previousReport,
    resolvedFindings,
    summary: {
      newFindingCount: newFindings.length,
      newHighOrCriticalCount: newFindings.filter((finding) => {
        return finding.severity === "critical" || finding.severity === "high";
      }).length,
      resolvedFindingCount: resolvedFindings.length,
      scoreDelta: Number(
        (currentReport.summary.score - previousReport.summary.score).toFixed(1),
      ),
      unchangedFindingCount: unchangedFindings.length,
    },
    unchangedFindings,
  };
}

export function buildCompareMarkdownSummary({
  comparison,
  currentLabel,
  previousLabel,
}: {
  comparison: WorkflowReportComparison;
  currentLabel: string;
  previousLabel: string;
}) {
  const lines = [
    "## Authos Compare Summary",
    "",
    `Current: ${currentLabel}`,
    `Previous: ${previousLabel}`,
    "",
    `- Score change: ${formatScoreDelta(comparison.summary.scoreDelta)}`,
    `- New findings: ${comparison.summary.newFindingCount}`,
    `- Resolved findings: ${comparison.summary.resolvedFindingCount}`,
    `- Unchanged findings: ${comparison.summary.unchangedFindingCount}`,
    `- New high/critical findings: ${comparison.summary.newHighOrCriticalCount}`,
  ];

  appendFindingSection(lines, "New findings", comparison.newFindings);
  appendFindingSection(lines, "Resolved findings", comparison.resolvedFindings);

  lines.push("", "_Generated by Authos locally._");

  return lines.join("\n");
}

function appendFindingSection(
  lines: string[],
  title: string,
  findings: AnalyzerFinding[],
) {
  lines.push("", `### ${title}`, "");

  if (findings.length === 0) {
    lines.push("- None");
    return;
  }

  for (const finding of findings.slice(0, 10)) {
    lines.push(
      `- [${finding.severity}] ${finding.ruleId} ${finding.title} (${formatFindingLocation(finding)})`,
    );
  }
}

function formatFindingLocation(finding: AnalyzerFinding) {
  return finding.location
    ? `${finding.filePath}:${finding.location.line}`
    : finding.filePath;
}

function formatScoreDelta(scoreDelta: number) {
  if (scoreDelta > 0) {
    return `+${scoreDelta}`;
  }

  return String(scoreDelta);
}

function normalizeFilePath(filePath: string) {
  return filePath.replace(/\\/gu, "/").toLowerCase();
}
