import { describe, expect, it } from "vitest";

import { sampleAnalysisReport } from "@/features/actions-analyzer/fixtures/reports";
import {
  buildHtmlReport,
  buildPrCommentMarkdown,
  buildSarifReport,
  serializeReportAsJson,
} from "@/features/actions-analyzer/lib/report-exports";

describe("report exports", () => {
  it("builds a markdown PR comment snapshot", () => {
    expect(buildPrCommentMarkdown(sampleAnalysisReport)).toMatchInlineSnapshot(`
      "## Authos Review: 90/100 (A)

      - Critical findings: 0
      - High findings: 0
      - Total findings: 2

      ### Top findings

      - [medium] GHA201 First-party reference uses a mutable tag (.github/workflows/release-risky.yml:7)
        First-party actions like actions/checkout@v4 commonly use version tags, but strict supply-chain reviews still prefer full SHA pins.
      - [medium] GHA100 Top-level permissions are not declared explicitly (.github/workflows/release-risky.yml)
        Declare top-level permissions explicitly so token access remains least-privilege and reviewable.

      ### Action pinning summary

      - Action references reviewed: 1
      - Unpinned references: 1
      - Privileged references: 0

      ### Permission summary

      - Workflows missing top-level permissions: 1
      - Recommended baseline: contents: read
      - Higher-review-risk jobs: 1

      _Generated by Authos locally on 2026-01-01T00:00:00.000Z._"
    `);
  });

  it("serializes the full report as JSON", () => {
    const serialized = serializeReportAsJson(sampleAnalysisReport);
    const parsed = JSON.parse(serialized) as typeof sampleAnalysisReport;

    expect(parsed.generatedAt).toBe(sampleAnalysisReport.generatedAt);
    expect(parsed.files[0]?.content).toContain("pull_request_target");
    expect(parsed.summary.score).toBe(sampleAnalysisReport.summary.score);
    expect(parsed.attackPaths[0]?.title).toBe(
      sampleAnalysisReport.attackPaths[0]?.title,
    );
  });

  it("builds a SARIF 2.1.0-like structure", () => {
    const sarif = buildSarifReport(sampleAnalysisReport);
    const [run] = sarif.runs;
    const [result] = run?.results ?? [];

    expect(sarif).toMatchObject({
      $schema: "https://json.schemastore.org/sarif-2.1.0.json",
      version: "2.1.0",
    });
    expect(run?.tool.driver.rules).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: "GHA100",
        }),
      ]),
    );
    expect(result).toMatchObject({
      level: "warning",
      message: {
        text: sampleAnalysisReport.findings[0]?.message,
      },
    });
    expect(result?.locations[0]?.physicalLocation.artifactLocation.uri).toBe(
      ".github/workflows/release-risky.yml",
    );
  });

  it("escapes user-controlled HTML content in the static report", () => {
    const html = buildHtmlReport({
      ...sampleAnalysisReport,
      findings: [
        {
          ...sampleAnalysisReport.findings[0]!,
          message: '<script>alert("xss")</script>',
          title: '<img src=x onerror="alert(1)" />',
        },
      ],
    });

    expect(html).not.toContain('<script>alert("xss")</script>');
    expect(html).not.toContain('<img src=x onerror="alert(1)" />');
    expect(html).toContain(
      "&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;",
    );
    expect(html).toContain("&lt;img src=x onerror=&quot;alert(1)&quot; /&gt;");
  });
});
