#!/usr/bin/env python3
"""Remove Authos branding from the repository."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {".git", "node_modules", ".next"}
SKIP_FILES = {"package-lock.json", "rebrand-remove-authos.py"}

TEXT_EXTENSIONS = {
    ".ts",
    ".tsx",
    ".md",
    ".json",
    ".mjs",
    ".yml",
    ".yaml",
    ".css",
    ".html",
}


def should_process(path: Path) -> bool:
    if path.name in SKIP_FILES:
        return False
    if path.suffix not in TEXT_EXTENSIONS and path.name not in {
        "README",
        "LICENSE",
    }:
        return False
    return not any(part in SKIP_DIRS for part in path.parts)


def rebrand(text: str) -> str:
    replacements = [
        ("authos-github-actions-workflow-analyzer", "github-actions-workflow-security-linter"),
        ("__authosCopiedTexts", "__ghaCopiedTexts"),
        ("cm-authos-", "cm-gha-"),
        ("# authos-ignore", "# gha-ignore"),
        ("authos-ignore", "gha-ignore"),
        ("https://authos.local", "http://127.0.0.1:3000"),
        ("authos.local", "127.0.0.1:3000"),
        ("authos.actions-analyzer", "gha-workflow-analyzer"),
        ("Authos GitHub Actions Analyzer", "GHA Workflow Security Linter"),
        ("Authos GitHub Actions Workflow Security and Lint Analyzer", "GitHub Actions Workflow Security Linter"),
        ("Authos developer tools", "GHA Workflow Security Linter"),
        ("Authos Tools", "GHA Workflow Security Linter"),
        ("Authos Analyzer", "GHA Workflow Security Linter"),
        ("## Authos Compare Summary", "## Workflow Compare Summary"),
        ("## Authos Review", "## Workflow Security Review"),
        ("Generated by Authos locally", "Generated locally"),
        ("Authos could not", "The analyzer could not"),
        ("Authos did not", "The analyzer did not"),
        ("Authos hit an", "The analyzer hit an"),
        ("Authos keeps a", "This tool keeps a"),
        ("Authos is using", "This tool is using"),
        ("Authos will not", "The analyzer will not"),
        ("Authos fetches", "This tool fetches"),
        ("Authos still does", "This tool still does"),
        ("Authos does not", "This tool does not"),
        ("Authos asks", "You will be asked"),
        ("Authos starts", "This tool starts"),
        ("Authos needs", "The analyzer needs"),
        ("Authos suggests", "The analyzer suggests"),
        ("Authos has a", "The analyzer has a"),
        ("Authos only", "The analyzer only"),
        ("Authos fetched", "This tool fetched"),
        ("Authos ignore", "GHA ignore"),
        ("inline Authos ignore", "inline GHA ignore"),
        ("to Authos.", "to this tool."),
        ("to Authos ", "to this tool "),
        ("content to Authos", "content to this server"),
        ("not uploaded to Authos", "not uploaded to any server"),
        ("The Authos workspace", "This workspace"),
        ("the Authos home page", "the home page"),
        ("Authos is starting with", "This product focuses on"),
        ("Authos is being built as", "This product is"),
        ("Authos ships focused", "This product ships focused"),
        ("live Authos tool", "live tool"),
        ("Authos tool catalog", "adjacent tools"),
        ("Authos tools are", "These tools are"),
        ("Core Authos tools", "Core tools"),
        ("Authos is a directory", "This site is"),
        ("Authos is a collection", "This is"),
        ("Authos is a browser-local", "This is a browser-local"),
        ("for the Authos analyzer", "for this analyzer"),
        ("Authos analyzer", "this analyzer"),
        ("Authos Ecosystem", "Project"),
        ("Other Authos tools", "Other related tools"),
        ("future Authos", "future multi-tool"),
        ("Authos-related", "GHA-related"),
        ("Authos product context", "project context"),
        ("Authos browser-based", "browser-based"),
        ("scaffolded the Authos home", "scaffolded the home"),
        ("credible Authos tools-directory", "credible tools-directory"),
        ("updating Authos", "updating the analyzer"),
        ("[Authos]", "[Analyzer]"),
        ("authos-workspace-report", "gha-workspace-report"),
        ("authos-workflow-report", "gha-workflow-report"),
        ("authos-report", "gha-report"),
        ("authosIgnorePattern", "ghaIgnorePattern"),
        (" - Authos", ""),
        ("(Authos tool 5)", "(standalone product)"),
        ('name: "Authos"', 'name: "GHA Workflow Analyzer"'),
        ('default: "Authos"', 'default: "GHA Workflow Analyzer"'),
        ('template: "%s | Authos"', 'template: "%s | GHA Workflow Analyzer"'),
        ('siteName: "Authos"', 'siteName: "GHA Workflow Analyzer"'),
        ('title: "Authos"', 'title: "GHA Workflow Analyzer"'),
        ("Authos | ", "GHA Workflow Analyzer | "),
        (">Authos<", ">GHA Workflow Analyzer<"),
        ("# Authos ", "# GHA Workflow "),
        ("Authos does **not**", "This tool does **not**"),
        ("Re-run analysis after updating Authos.", "Re-run analysis after updating this tool."),
        ("`authos - apps/tools`", "`related-tools`"),
        ("| `authos` |", "| (legacy) |"),
        ("| `authos-terraform", "| `terraform"),
        ("Authos ", "GHA Workflow Analyzer "),
        ("Authos.", "This tool."),
        ("Authos,", "This tool,"),
        ("Authos\n", "GHA Workflow Analyzer\n"),
        ("Authos", "GHA Workflow Analyzer"),
        ("authos-", "gha-"),
    ]

    for old, new in replacements:
        text = text.replace(old, new)

    return text


def main() -> None:
    changed: list[str] = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or not should_process(path):
            continue
        original = path.read_text(encoding="utf-8")
        updated = rebrand(original)
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            changed.append(str(path.relative_to(ROOT)))

    print(f"Updated {len(changed)} files")
    remaining = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or not should_process(path):
            continue
        if re.search(r"authos", path.read_text(encoding="utf-8"), re.IGNORECASE):
            remaining.append(str(path.relative_to(ROOT)))

    if remaining:
        print(f"Still contains authos ({len(remaining)}):")
        for item in sorted(remaining)[:40]:
            print(f"  - {item}")
    else:
        print("No authos references remain.")


if __name__ == "__main__":
    main()
