import type { RuleModule } from "@/features/actions-analyzer/types";

import {
  malformedExpressionRule,
  matrixOutsideMatrixJobRule,
  secretsInIfRule,
  unknownContextRule,
  unknownNeedsExpressionRule,
  untrustedContextRule,
} from "@/features/actions-analyzer/lib/rules/expression.rules";
import {
  invalidPermissionsRule,
  invalidRunsOnRule,
  invalidTimeoutRule,
  missingRunsOnOrUsesRule,
  reusableWorkflowMixedFieldsRule,
  unknownNeedsRule,
} from "@/features/actions-analyzer/lib/rules/job-semantics.rules";
import { noFilesRule } from "@/features/actions-analyzer/lib/rules/no-files.rule";
import {
  broadWritePermissionsRule,
  longLivedCloudSecretRule,
  missingTopLevelPermissionsRule,
  privilegedThirdPartyActionRule,
  pullRequestTargetCheckoutRule,
  pullRequestTargetRule,
  secretsInWorkflowOrJobEnvRule,
  selfHostedPullRequestRule,
  topLevelWriteAllRule,
  untrustedDeploymentRule,
  workflowRunPrivilegeRule,
} from "@/features/actions-analyzer/lib/rules/security.rules";
import {
  malformedUsesRule,
  stepMissingRunOrUsesRule,
  stepRunAndUsesRule,
} from "@/features/actions-analyzer/lib/rules/step-semantics.rules";
import {
  branchReferenceRule,
  checkoutPersistedCredentialsRule,
  dockerDigestRule,
  dynamicUsesReferenceRule,
  firstPartyMutableTagRule,
  latestTagRule,
  privilegedThirdPartyReferenceRule,
  shortShaRule,
  thirdPartyUnpinnedRule,
} from "@/features/actions-analyzer/lib/rules/supply-chain.rules";
import {
  duplicateJobIdsRule,
  invalidJobsShapeRule,
  missingJobsRule,
  missingOnRule,
  suspiciousKeyTypoRule,
} from "@/features/actions-analyzer/lib/rules/workflow-structure.rules";

export const registeredRuleModules: RuleModule[] = [
  noFilesRule,
  missingOnRule,
  missingJobsRule,
  invalidJobsShapeRule,
  missingRunsOnOrUsesRule,
  stepRunAndUsesRule,
  stepMissingRunOrUsesRule,
  malformedUsesRule,
  unknownNeedsRule,
  duplicateJobIdsRule,
  invalidPermissionsRule,
  invalidRunsOnRule,
  invalidTimeoutRule,
  reusableWorkflowMixedFieldsRule,
  suspiciousKeyTypoRule,
  malformedExpressionRule,
  unknownContextRule,
  secretsInIfRule,
  matrixOutsideMatrixJobRule,
  unknownNeedsExpressionRule,
  untrustedContextRule,
  missingTopLevelPermissionsRule,
  topLevelWriteAllRule,
  broadWritePermissionsRule,
  pullRequestTargetRule,
  pullRequestTargetCheckoutRule,
  selfHostedPullRequestRule,
  workflowRunPrivilegeRule,
  secretsInWorkflowOrJobEnvRule,
  longLivedCloudSecretRule,
  untrustedDeploymentRule,
  privilegedThirdPartyActionRule,
  thirdPartyUnpinnedRule,
  firstPartyMutableTagRule,
  branchReferenceRule,
  shortShaRule,
  dockerDigestRule,
  dynamicUsesReferenceRule,
  checkoutPersistedCredentialsRule,
  latestTagRule,
  privilegedThirdPartyReferenceRule,
];
